import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      maxWidth: {
        site: '1440px',
        content: '1280px',
        reading: '760px',
        text: '680px',
        hero: '720px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '32px',
        '8': '40px',
        '9': '48px',
        '10': '56px',
        '11': '64px',
        '12': '72px',
        '13': '80px',
        '14': '96px',
        '15': '120px',
        '16': '144px',
        '17': '160px',
        '18': '192px',
        '19': '256px',
      },
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        primary: 'var(--primary)',
        'primary-secondary': 'var(--primary-secondary)',
        'primary-accent': 'var(--primary-accent)',
        text: 'var(--text)',
        'text-secondary': 'var(--text-secondary)',
        muted: 'var(--text-muted)',
        border: 'var(--border)',
        glass: 'var(--glass)',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        '2xl': '24px',
        glass: '28px',
        full: '999px',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-ibm-plex-mono)', 'JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        display: ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'h1': ['56px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'h2': ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'h3': ['40px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'h4': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'h5': ['24px', { lineHeight: '1.3', letterSpacing: '0' }],
        'h6': ['20px', { lineHeight: '1.3', letterSpacing: '0' }],
        'body-lg': ['18px', { lineHeight: '1.7' }],
        'body': ['16px', { lineHeight: '1.7' }],
        'small': ['14px', { lineHeight: '1.6' }],
        'caption': ['13px', { lineHeight: '1.6' }],
        'tiny': ['12px', { lineHeight: '1.6' }],
      },
      boxShadow: {
        soft: '0 8px 30px rgba(0,0,0,0.18)',
        medium: '0 16px 40px rgba(0,0,0,0.28)',
        large: '0 24px 60px rgba(0,0,0,0.36)',
        floating: '0 30px 80px rgba(0,0,0,0.45)',
        glass: '0 20px 60px rgba(0,0,0,0.35)',
      },
      backdropBlur: {
        glass: '20px',
      },
      transitionDuration: {
        fast: '150ms',
        normal: '250ms',
        medium: '400ms',
        slow: '600ms',
        aurora: '30s',
        theme: '500ms',
      },
      transitionTimingFunction: {
        'ease-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'ease-in-out': 'cubic-bezier(0.65, 0, 0.35, 1)',
      },
      zIndex: {
        background: '-10',
        aurora: '-5',
        content: '1',
        cards: '5',
        nav: '100',
        drawer: '500',
        modal: '1000',
        toast: '1200',
      },
      animation: {
        'aurora-1': 'aurora-drift-1 30s ease-in-out infinite',
        'aurora-2': 'aurora-drift-2 40s ease-in-out infinite',
        'aurora-3': 'aurora-drift-3 35s ease-in-out infinite',
      },
      keyframes: {
        'aurora-drift-1': {
          '0%, 100%': { transform: 'translateX(-10%) rotate(0deg) scaleY(1)' },
          '50%': { transform: 'translateX(10%) rotate(2deg) scaleY(1.5)' },
        },
        'aurora-drift-2': {
          '0%, 100%': { transform: 'translateX(10%) rotate(0deg) scaleY(1.2)' },
          '50%': { transform: 'translateX(-10%) rotate(-2deg) scaleY(1.8)' },
        },
        'aurora-drift-3': {
          '0%, 100%': { transform: 'translateX(-5%) translateY(0) scaleY(1)' },
          '50%': { transform: 'translateX(5%) translateY(-20px) scaleY(1.3)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
